language: node_js
node_js:
    - 10
cache:
    directories:
        - node_modules
script:
    - npm run test:unit
after_script:
    - cat ./coverage/lcov.info | coveralls
    - npm run build
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
    local_dir: /dist
    keep_history: true
    on:
        branch: master
