language: node_js
node_js:
    - 10
cache:
    directories:
        - node_modules
script:
    - npm run test:unit
after_script:
    - cat ./coverage/lcov.info | coveralls
    - npm run build
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist
    on:
        branch: master
