language: node_js
node_js:
    - 10
cache:
    directories:
        - node_modules
script:
    - npm run test:unit
after_script:
    - cat ./coverage/lcov.info | coveralls
before_deploy:
    - git config --local user.name "$GITHUB_LOGIN"
    - git config --local user.email "$GITHUB_PW"
deploy:
    provider: script
    skip_cleanup: true
    script: bash ./deploy.sh
    on:
        branch: master
